import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
let source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/init\(\)\.catch\([\s\S]*$/,'');
const context={console,document:{getElementById:()=>null},localStorage:{}};context.window=context;vm.createContext(context);vm.runInContext(source,context);
const roster=[{name:'QB',pos:'QB',value:80,rank:1},{name:'RB',pos:'RB',value:70,rank:2},{name:'Kicker',pos:'K',value:20,rank:251},{name:'Defense',pos:'DST',value:18,rank:252}];
let lineup=context.optimalLineup(roster,{QB:0,RB:0,WR:0,TE:0,FLEX:0,SF:1,K:1,DST:1});
assert.equal(lineup.lineup.find(x=>x.slot==='SF').player.name,'QB');
assert.equal(lineup.lineup.find(x=>x.slot==='K').player.name,'Kicker');
assert.equal(lineup.lineup.find(x=>x.slot==='DST').player.name,'Defense');
lineup=context.optimalLineup(roster.filter(p=>['K','DST'].includes(p.pos)),{QB:0,RB:0,WR:0,TE:0,FLEX:0,SF:1,K:0,DST:0});
assert.equal(lineup.lineup[0].player,null,'K and D/ST must never fill Superflex');
console.log('My Team K/DST and Superflex eligibility tests passed');
