#!/usr/bin/env python3
"""Fit first Roster Report next-season projection models.

Input files are generated by build-nflverse-features.py. The training target is
NEXT-season PPR points per game, not same-season fantasy points. We use a small
ridge model with season holdout because the current historical window has only
2023->2024 and 2024->2025 transitions.

The model intentionally favors stable opportunity/efficiency metrics and keeps
all coefficients auditable in JSON.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import numpy as np
import pandas as pd

ALPHAS = [0.1, 1.0, 10.0, 50.0, 100.0]

FEATURES = {
    "QB": [
        "games", "attempts", "completion_rate", "pass_yards_per_attempt",
        "pass_yac_share", "pass_td_rate", "interception_rate",
        "sacks_per_attempt", "passing_epa_per_attempt", "carries_per_game",
        "yards_per_carry", "rush_td_per_attempt", "rushing_epa_per_attempt",
        "ppr_per_game",
    ],
    "RB": [
        "games", "carries_per_game", "yards_per_carry", "rush_td_per_attempt",
        "rushing_first_down_rate", "rushing_epa_per_attempt", "targets_per_game",
        "target_share", "catch_rate", "yards_per_target", "rec_td_per_target",
        "receiving_first_down_rate", "receiving_epa_per_target", "ppr_per_game",
    ],
    "WR": [
        "games", "targets_per_game", "target_share", "air_yards_share", "wopr",
        "catch_rate", "yards_per_target", "air_yards_per_target",
        "yac_per_reception", "rec_td_per_target", "receiving_first_down_rate",
        "receiving_epa_per_target", "ppr_per_game",
    ],
    "TE": [
        "games", "targets_per_game", "target_share", "air_yards_share", "wopr",
        "catch_rate", "yards_per_target", "air_yards_per_target",
        "yac_per_reception", "rec_td_per_target", "receiving_first_down_rate",
        "receiving_epa_per_target", "ppr_per_game",
    ],
}


def standardize_fit(df: pd.DataFrame, features: list[str]):
    x = df[features].apply(pd.to_numeric, errors="coerce")
    means = x.mean()
    stds = x.std(ddof=0).replace(0, 1).fillna(1)
    x = x.fillna(means).fillna(0)
    return (x - means) / stds, means, stds


def standardize_apply(df: pd.DataFrame, features, means, stds):
    x = df[features].apply(pd.to_numeric, errors="coerce")
    x = x.fillna(means).fillna(0)
    return (x - means) / stds


def ridge_fit(x: np.ndarray, y: np.ndarray, alpha: float):
    # Intercept is handled separately and not penalized.
    x1 = np.column_stack([np.ones(len(x)), x])
    penalty = np.eye(x1.shape[1]) * alpha
    penalty[0, 0] = 0
    return np.linalg.pinv(x1.T @ x1 + penalty) @ x1.T @ y


def predict(x: np.ndarray, beta: np.ndarray):
    return np.column_stack([np.ones(len(x)), x]) @ beta


def metrics(y, p):
    err = p - y
    mae = float(np.mean(np.abs(err)))
    rmse = float(np.sqrt(np.mean(err ** 2)))
    corr = float(np.corrcoef(y, p)[0, 1]) if len(y) > 1 and np.std(y) > 0 and np.std(p) > 0 else None
    return {"n": int(len(y)), "mae": mae, "rmse": rmse, "correlation": corr}


def fit_position(path: Path, pos: str):
    df = pd.read_csv(path)
    df = df[df["next_ppr_per_game"].notna()].copy()
    wanted = [f for f in FEATURES[pos] if f in df.columns]
    if len(df) < 10 or not wanted:
        raise RuntimeError(f"Insufficient {pos} training data: n={len(df)}, features={len(wanted)}")

    # Validate by learning 2024 outcomes only from 2023 inputs, then predicting
    # 2025 outcomes from 2024 inputs. If one split is sparse, fall back to a
    # deterministic 75/25 chronological split.
    train = df[df["season"].eq(2023)]
    valid = df[df["season"].eq(2024)]
    if len(train) < 8 or len(valid) < 5:
        df = df.sort_values(["season", "player_id"])
        cut = max(1, int(len(df) * 0.75))
        train, valid = df.iloc[:cut], df.iloc[cut:]

    xtr, means, stds = standardize_fit(train, wanted)
    xva = standardize_apply(valid, wanted, means, stds)
    ytr = train["next_ppr_per_game"].to_numpy(float)
    yva = valid["next_ppr_per_game"].to_numpy(float)

    trials = []
    for alpha in ALPHAS:
        beta = ridge_fit(xtr.to_numpy(float), ytr, alpha)
        m = metrics(yva, predict(xva.to_numpy(float), beta))
        trials.append((m["rmse"], alpha, m))
    _, best_alpha, holdout = min(trials, key=lambda x: x[0])

    # Refit the selected regularization on every available transition.
    xall, means, stds = standardize_fit(df, wanted)
    yall = df["next_ppr_per_game"].to_numpy(float)
    beta = ridge_fit(xall.to_numpy(float), yall, best_alpha)
    fitted = metrics(yall, predict(xall.to_numpy(float), beta))

    coef = {name: float(value) for name, value in zip(wanted, beta[1:])}
    ranked = sorted(coef.items(), key=lambda kv: abs(kv[1]), reverse=True)
    return {
        "position": pos,
        "target": "next_ppr_per_game",
        "training_seasons": [2023, 2024],
        "best_alpha": best_alpha,
        "features": wanted,
        "intercept": float(beta[0]),
        "coefficients_standardized": coef,
        "feature_means": {k: float(v) for k, v in means.items()},
        "feature_stds": {k: float(v) for k, v in stds.items()},
        "holdout_metrics": holdout,
        "refit_metrics": fitted,
        "importance_order": [name for name, _ in ranked],
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=Path("data/projections"))
    parser.add_argument("--out", type=Path, default=Path("data/projections/model_coefficients_v0_1.json"))
    args = parser.parse_args()

    models = {}
    for pos in ["QB", "RB", "WR", "TE"]:
        path = args.data_dir / f"training_{pos.lower()}_next_season.csv"
        models[pos] = fit_position(path, pos)
        print(pos, models[pos]["holdout_metrics"], models[pos]["importance_order"][:5])

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps({"version": "0.1", "models": models}, indent=2))
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
